### ISSUE TITLE
Soundcloud playlist URL importing problem[BUG]

### ISSUE THREAD

**Issue by alpharash** [Moosync/Moosync#100]
i think there is a issue with importing url's ftom soundcloud playlists that only top 5 songs of the playlist is showing and only top 5 songs are imported in playlist. no matter how songs are in playlist only top 5 are showed.
![image_2022-06-28_010141646](https://user-images.githubusercontent.com/23490636/176030440-6eec1c8f-22e0-4335-b7c0-f92dca66d005.png)

**Comment by Ovenoboyo** [comment]
Thanks for reporting this bug. Turns out the library I was using for fetch data from Soundcloud was very unreliable. I've managed to rewrite it completely. Hoping that should make the process faster and fix this bug

(https://github.com/Ovenoboyo/moosync-soundcloud/commit/e906742dfc920403798aa110b04e656599f00485)

**Comment by tr1p0p** [comment]
I think the commit make it worst and now you cannot add soundcloud playlist at all on last version.

**Comment by tr1p0p** [comment]
[Capture vidéo du 2023-01-25 18-36-36.webm](https://user-images.githubusercontent.com/37407065/214639655-eaf5041e-8b5b-44ad-8007-eb7fd29681cb.webm)

**Comment by Ovenoboyo** [comment]
Hey sorry for the late reply, but this is a problem in the main app itself it seems

**Comment by Ovenoboyo** [comment]
It should be fixed in a3399c3427498479f6fbf23e9929dda8d4bc9d08
