### ISSUE TITLE
[feature] option to get thumbnails from the local file's metadata, as opposed to musicbrainz

### ISSUE THREAD

**Issue by t3dium** [Moosync/Moosync#149]

**Comment by Ovenoboyo** [comment]
By default thumbnails for songs are fetched from the file's metadata. Musicbrainz is only used to fetch thumbnails for artists since there is no standard format to store artist's thumbnails in song's metadata (I could be wrong). Do you know of any alternative or a location from where we could get an artist's cover images?

**Comment by t3dium** [comment]
> By default thumbnails for songs are fetched from the file's metadata. Musicbrainz is only used to fetch thumbnails for artists 

ah you're right, thumbnails show now even when not having internet, previously it wasn't showing not sure why
