### ISSUE TITLE
[BUG] Mpris works ,but not how it should

### ISSUE THREAD

**Issue by rebokdev** [Moosync/Moosync#190]
**Describe the bug**
When my music plays then mpris controls disappear ,but when i pause it controls are being shown.
There's also one thing when they are shown, when i click play/pause nothing happens

**To Reproduce**

1. Play some music
2. Check gnome notifications & calendar panel(first occurrence)(it isn't shown)
3. pause the music
4. Check gnome notifications & calendar panel(second occurrence)(it is shown)

**Expected behavior**

- Mpris controls when music is playing
- Mpris play/pause button working

- OS: [e.g. Linux] Fedora 37 workstation
- Version v5.1.0(flatpak)

**Comment by Ovenoboyo** [comment]
Sorry for the inconvenience. This seems related to #184. Could you try the build from https://github.com/Moosync/Moosync/actions/runs/3802481594 (You'll need to be logged in to GitHub to be able to download the build). Unfortunately there's no flatpak builds on the CI.

If this bug is not a deal breaker, I'll be pushing out an update by the end of this week.

**Comment by Ovenoboyo** [comment]
I'll be closing this issue since it seems to be fixed. Feel free to reopen it if you feel otherwise.
