### ISSUE TITLE
[FEATURE] Export/Import Theme 

### ISSUE THREAD

**Issue by Spaxly** [Moosync/Moosync#198]
It would be really useful for colorschemes like Catppuccin to easily add a port for this as you can export/import themes within seconds instead of manually adding the colors.

**Comment by Ovenoboyo** [comment]
There is a method to export the themes actually. You can right click on any theme and select "copy to clipboard".
If you have a Moosync theme copied to clipboard, and you click on "new theme", it will try to import colors from that theme.

But I understand this isn't really intuitive. Do you have any suggestions on how this could be improved?

**Comment by Ovenoboyo** [comment]
I'll also have a look at Catppuccin and see how their other ports work

**Comment by Spaxly** [comment]
An option to export a selected theme and output that to a config file would be great. Then, importing that config file into the application following the contents of the file.

**Comment by Ovenoboyo** [comment]
Its taking a bit longer than expected since there's also #196 which implements custom css. I'll try to get it done this weekend

**Comment by Ovenoboyo** [comment]
It still needs some work on the import UI but this is how the general import / export flow will work

To export a theme,
- Right click on it under settings > themes
- Select export theme
- Save the theme from the save dialog

To import a theme,
- Click on the import button (Need to work out its placement)
- Select the file exported above

The exported theme will be a zip file with an extension of .mstx (For clarity). It wasn't possible to just export a single config file due to inclusion of custom CSS.

**Comment by Spaxly** [comment]
Nice, hyped to see how it comes out.
