### ISSUE TITLE
[BUG] Not properly terminated

### ISSUE THREAD

**Issue by maboroshin** [Moosync/Moosync#212]
**Describe the bug**

The instance remains even after Moosync is closed.

**To Reproduce**

1. Close Moosync Portable on Win10. 
2. 8 Moosync instances remain on Task Manager:

![Task Manager after Moosync is terminated](https://user-images.githubusercontent.com/41102508/225252122-58276af8-03cd-4d4c-855a-407e93fb9e5d.png)

When the portable is execute again, there will be one instance.

**Expected behavior**
Moosync instance will be 0 after Moosync is terminated.

**Screenshots**
Above.

- OS: Win10
- Version 22H2

**Comment by Ovenoboyo** [comment]
Under settings > system, there is a toggle called "minimize to tray". I believe this is what's happening in your case. By default when you close the app, it will minimize to your taskbar tray instead of exiting. To completely exit the app you'll need to right click on the tray icon and select "quit". You can turn off this behaviour through the above toggle.

Let me know if this isn't the case with you

**Comment by maboroshin** [comment]
Thank you. Sorry. This setting was on.
