### ISSUE TITLE
[BUG] playerctl play-pause will start playing song even if the queue is empty

### ISSUE THREAD

**Issue by JZITNIK-github** [Moosync/Moosync#267]
**Describe the bug**
When i clear the queue and run `playerctl play-pause` it will start playing last played song even if the queue is empty. And also if i play another video for example from youtube the playerctl will still start playing the song in moosync and not pausing the video from youtube as I would expect.

**To Reproduce**

1. Play any song
2. Go to queue
3. Click on 'Clear'
4. Run 'playerctl play-pause'

**Expected behavior**
I would expect playerctl not to play a song if there is none in the queue. I would also expect that if I start another song/video in another program, playerctl would not start moosync but the video being played.

**Screenshots**
Recording:
https://github.com/Moosync/Moosync/assets/72742578/062cee1c-6458-4bd6-b738-45bd76b5966a

- OS: Arch Linux
- Version: v10.0.0

**Comment by Ovenoboyo** [comment]
I've fixed the bug when playerctl would start playing the last song when the queue was empty. You can find the development builds in [Github Actions](https://github.com/Moosync/Moosync/actions/workflows/build.yml)

As for playerctl controlling moosync when there's nothing playing, seems to be the normal behavior of playerctl . Playerctl will select the first media player by default (unless specified through --player). When moosync is simply open and not playing any tracks, it is still capable of receiving events from MPRIS (like repeat, shuffle, etc) which is why it does not close the established connection when the queue is cleared
