### ISSUE TITLE
It is not possible to import playlists with the .m3u that I export from Moosync

### ISSUE THREAD

**Issue by Terkyz** [Moosync/Moosync#79]
**Describe the bug**
As the title says, it is not possible to import playlists in .m3u and .m3u8 that I previously exported using Moosync

**To Reproduce**
After exporting said playlist in an .m3u and trying to import it to a completely new Moosync instance by adding the .m3u to /Home/User/Music, the file is not detected directly, even when renaming its extension to .m3u8

**Expected behavior**
That my playlist be imported as exported.

**Screenshots**
https://imgur.com/a/tGv7toQ

- OS: Debian 11.3

**Additional context**
In my case, my original playlist had both downloaded music and online music that I added using Moosync.

**Comment by Ovenoboyo** [comment]
Since m3u is a standard playlist format, we would only be exporting local songs along with it. M3U requires a direct stream URL or a filepath to be stored in it while we use Youtube embeds to play music directly using videoIDs from Youtube.

This is why at this moment exporting non-local songs would be difficult in a M3U.

**Comment by Ovenoboyo** [comment]
Instead for the specific case of backup and restore, I would be implementing a separate feature. See #81

**Comment by Ovenoboyo** [comment]
But I'll still attempt to get this working

**Comment by Ovenoboyo** [comment]
It should be possible to export and import playlists with remote songs from version >2.0.0
